variables:
  crystal_image: crystallang/crystal:0.29.0

stages:
  - build-and-test
  - package

cache:
  paths:
    - lib

build-and-test:
  stage: build-and-test
  image: crystallang/crystal:0.29.0
  script:
    - apt-get update -qq && apt-get install -y -qq libxml2-dev
    - shards install
    - shards build -v

package:
  stage: package
  image: jrei/crystal-alpine
  script: 
    - shards install
    - shards build --production --release --static
  artifacts:
    paths:
      - bin/bot
    expire_in: 1 week
  
docker-image:
  stage: package
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_SHA:0:6} .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_SHA:0:6}
